name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Test
      id: test
      uses: classroom-resources/autograding-python-grader@v1
      with:
        timeout: 10
        max-score: 1
        setup-command: pip3 install -r requirements.txt
    - name: Test changed
      id: test-changed
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Test changed
        setup-command: pip3 install -r requirements.txt
        command: python3 test.py
        timeout: 10
        max-score: 1
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        TEST_RESULTS: "${{steps.test.outputs.result}}"
        TEST-CHANGED_RESULTS: "${{steps.test-changed.outputs.result}}"
      with:
        runners: test,test-changed
